### ISSUE TITLE
Use service labels

### ISSUE THREAD

**Issue by vfarcic** [thomasjpfan/docker-scaler#1]
Scaler currently uses container, not service labels to deduce minimum and maximum number of replicas. Please add the usage of service labels as well. You can test them by moving labels from the test service into the deploy section.

From:

```
  web:
    image: alpine:3.6
    labels:
      com.df.scaleMin: "2"
      com.df.scaleMax: "4"
    deploy:
      replicas: 3
    command: sleep 10000000
```

to:

```
  web:
    image: alpine:3.6
    deploy:
      replicas: 3
      labels:
        com.df.scaleMin: "2"
        com.df.scaleMax: "4"
    command: sleep 10000000
```
