### ISSUE TITLE
Use POST body instead of URL query parameters

### ISSUE THREAD

**Issue by thomasjpfan** [thomasjpfan/docker-scaler#5]
This allows us to simplify the configuration for the Alertmanager, since the POST request body already has all the information needed:

```
{
  "version": "4",
  "groupKey": <string>,    // key identifying the group of alerts (e.g. to deduplicate)
  "status": "<resolved|firing>",
  "receiver": <string>,
  "groupLabels": <object>,
  "commonLabels": <object>,
  "commonAnnotations": <object>,
  "externalURL": <string>,  // backlink to the Alertmanager.
  "alerts": [
    {
      "labels": <object>,
      "annotations": <object>,
      "startsAt": "<rfc3339>",
      "endsAt": "<rfc3339>"
    },
    ...
  ]
}
```

https://prometheus.io/docs/alerting/configuration/

**Comment by thomasjpfan** [comment]
I think it would be better to move all parameters out of the URL query and use the POST body's `groupLabels` to indicate scaling up or down. Furthermore moving the `delta` parameter into a service label such as `com.df.deltaUp=1` and `com.df.deltaDown=-1`. For example:

```yaml
services:
  main:
    image: vfarcic/go-demo
    ...
    labels:
      - com.df.deltaUp=1
      - com.df.deltaDown=-1
    ...
```

Currently, if we want to change the alertmanager configuration, we would need to turn remove the alertmanager service, remove the `alert_manager_config ` secret, add a new secret, start up the service again. This change would allow for the `alert_manager_config` secret to change less often. It can look something like this:

```
route:
  group_by: [service, scale]
  repeat_interval: 5m
  group_interval: 5m
  receiver: 'slack'
  routes:
  - match_re:
      scale: ^(up|down)$
    receiver: 'scale'

receivers:
  ...
  - name: 'scale'
    webhook_configs:
      - send_resolved: false
        url: 'http://scaler:8080/v1/scale-service'
...
```

What do you think @vfarcic?
